### ISSUE TITLE
Passing through params to users service

### ISSUE THREAD

**Issue by vonagam** [feathers-plus/feathers-authentication-management#107]
I have a user service which uses knex adapter.

In before hook i start knex transaction with [`transaction.start()`](https://github.com/feathersjs-ecosystem/feathers-knex#transaction-support).

In after hook for `create` method i "create" `resendVerifySignup` before `transaction.end`, so that transaction will be rolled back if there is some error during email sending.

Because user is created inside transaction, to [find](https://github.com/feathers-plus/feathers-authentication-management/blob/7d5234b0953e38dec797b8246c1416b2efe0bf73/src/resendVerifySignup.js#L34) or [patch](https://github.com/feathers-plus/feathers-authentication-management/blob/7d5234b0953e38dec797b8246c1416b2efe0bf73/src/resendVerifySignup.js#L52) him you need to pass `transaction` param to users service inside `authentication-management` calls.

So `users.find({query, transaction})` instead of simple `users.find({query})`.

Currently it is not possible.

What your thoughts on adding new option, for example `serviceParams`, to specify which params get passed through to users service?

**Comment by eddyystop** [comment]
I'm planning to rewrite this repo this year. async/await instead of promises, prop values compatible with all DBs, etc.

I'll consider all outstanding issues at that point.

I assume this comment in https://github.com/feathers-plus/feathers-authentication-management/pull/108 will handle this issue:
"Options will include functions for overriding all service calls made by the repo. This is something we learned with feathers-hooks-common, e.g. fastJoin instead of populate."

**Comment by eddyystop** [comment]
This feature has been implemented in the authentication-local-management rewrite. Full details are posted to https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

Please post any comments or issues in a-l-m.
