### ISSUE TITLE
Notifier wont work with other opitions like 'identifyUserProps'

### ISSUE THREAD

**Issue by guzz** [feathers-plus/feathers-authentication-management#120]
### Steps to reproduce

I am configuring authManagement in my app like this:

```
app.configure(authManagement({
    notifier: () => notifier(app),
    identifyUserProps: ['email', 'phone']
  }));
```

But notifier is not called when I make any actions from client like `sendResetPwd`.

If I configure it like this:

```
app.configure(authManagement(notifier(app)));
```

It will work, but them I cant use the phone as a identifying property to my users.

**Comment by guzz** [comment]
Ok I figured out what I was doing wrong:

My notifier was actualy returning an object I just changed it to export the function.

That was stupid.

**Comment by gchokeen** [comment]
Hi Guzz, I'm facing the same [issue](https://github.com/feathers-plus/feathers-authentication-management/issues/125), can you elaborate the solution,

My notifier js looks similar to this 

``` 
module.exports = function(app) {

  function getLink(type, hash) {
    const url = 'http://localhost:3030/' + type + '?token=' + hash
    return url
  }

  function sendEmail(email) {
    return app.service('mailer').create(email).then(function (result) {
      console.log('Sent email', result)
    }).catch(err => {
      console.log('Error sending email', err)
    })
  }

  return {
    notifier: function(type, user, notifierOptions) {
      let tokenLink
      let email
      switch (type) {
        case 'resendVerifySignup': //sending the user the verification email
          tokenLink = getLink('verify', user.verifyToken)
          email = {
             from: process.env.FROM_EMAIL,
             to: user.email,
             subject: 'Verify Signup',
             html: tokenLink
          }
          return sendEmail(email)
          break

        case 'verifySignup': // confirming verification
          tokenLink = getLink('verify', user.verifyToken)
          email = {
             from: process.env.FROM_EMAIL,
             to: user.email,
             subject: 'Confirm Signup',
             html: 'Thanks for verifying your email'
          }
          return sendEmail(email)
          break

        case 'sendResetPwd':
          tokenLink = getLink('reset', user.resetToken)
          email = {}
          return sendEmail(email)
          break

        case 'resetPwd':
          tokenLink = getLink('reset', user.resetToken)
          email = {}
          return sendEmail(email)
          break

        case 'passwordChange':
          email = {}
          return sendEmail(email)
          break

        case 'identityChange':
          tokenLink = getLink('verifyChanges', user.verifyToken)
          email = {}
          return sendEmail(email)
          break

        default:
          break
      }
    }
  }
}
 ```
Config look like this 

```

  const options = {
    identifyUserProps,
    shortTokenLen,
    shortTokenDigits,
    notifier: () => notifier(app),
   
  };

  app.configure(authManagement(options));
```

Please can you tell me how to fix it?

**Comment by janzheng** [comment]
haha I did the same thing (probably used the same tutorial!)

@gchokeen this is probably too late, but instead of doing this, which returns an object:
```
return {
    notifier: function(type, user, notifierOptions) {
```
you return the notifier as a function:
```
return function(type, user, notifierOptions) {
```

**Comment by user-2015-r** [comment]
@janzheng Could you please explain? I still have this issue.

**Comment by chrisbag** [comment]
Hello, 
I am experiencing the same issue as described @guzz.
I am unable to modify options.identifyUserProps as well as use notifier (I am using feathers with Typescript)

**The following  works but I cannot change default identifyUserProps to use username instead of email.**
**authmanagement.services.ts**

`import { ServiceAddons } from '@feathersjs/feathers'
import authManagement from 'feathers-authentication-management'
import { Application } from '../../declarations'
import hooks from './authmanagement.hooks'
import notifier from './notifier'

// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    authManagement: ServiceAddons<any>
  }
}

export default function(app: Application): void {
  app.configure(authManagement(notifier(app)))

  const service = app.service('auth-management')

  // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
  // @ts-ignore // seems like ts thinks that service doesn't exist
  service.hooks(hooks)
}`


**Trying to change default options gives me the following error : TypeError: Cannot read property 'hooks' of undefined**

**authmanagement.services.ts**

`import { ServiceAddons } from '@feathersjs/feathers'
import authManagement from 'feathers-authentication-management'
import { Application } from '../../declarations'
import hooks from './authmanagement.hooks'
import notifier from './notifier'

// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    authManagement: ServiceAddons<any>
  }
}

export default function(app: Application): void {
  const options = {
    identifyUserProps: ['id', 'username'],
    notifier: () => notifier(app),
  }
  app.configure(authManagement(options))

  const service = app.service('auth-management')

  // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
  // @ts-ignore // seems like ts thinks that service doesn't exist
  service.hooks(hooks)
}
`


Would you have any idea of the solution ?
Thanks a lot for your help.

**Comment by claustres** [comment]
The expected `notifier` option should be your notifier function directly, so something like:
```
const notifier = function(type, user, notifierOptions) { ... }

app.configure(authManagement({
  notifier,
  ...
}))
```

I guess you are using this [tutorial](https://hackernoon.com/setting-up-email-verification-in-feathersjs-ce764907e4f2) and the notifier function is actually wrapped in a module exporting a closure in order to get access to the app. That's the reason of the way it is written `app.configure(authManagement(notifier(app)))`. The call `notifier(app)` actually returns an object like this `{ notifier }`. So take care the way you are exporting/importing your notifier function.

**Comment by chrisbag** [comment]
@claustres 
Thank you for your fast answer, this is exactly what happened.
Problem solved :)
