### ISSUE TITLE
Review article for pain points

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-authentication-management#13]
https://medium.com/@codingfriend/how-to-setup-email-verification-in-feathersjs-72ce9882e744#.myaj0fvkx

Review the article for things we could improve.

**Comment by JZiebikiewicz** [comment]
Great article!

1) What hook is ```globalHooks.isEnabled()```?
2) Could you also write about hooks we need for the newest feathers-authentication (v1)? These are deprecated:
```js
auth.verifyToken(),
auth.populateUser(),
auth.restrictToAuthenticated(),
```
Instead of two first we can use just ```auth.hooks.authenticate('jwt')```.

3) In responses I get all user's data. No info about success nor fail of request. My mistake somewhere or it is correct?

**Comment by eddyystop** [comment]
I think we have a misunderstanding. LOL. We didn't write the article, someone else did. I opened this issue as a reminded to see what we could do that would have made that article shorter or the work needed easier.

As far a auth docs go, please create an issue in feathers-authentication. Thanks.
