### ISSUE TITLE
Expected string value. (authManagement)

### ISSUE THREAD

**Issue by farhad-arjmand** [feathers-plus/feathers-authentication-management#137]
```
changePassword({ commit }, {email,oldPassword,password}) {
    return new Promise((resolve, reject) => {
      let data = {
        'action': 'passwordChange',
        'value': {

          'user': {
            email: email
          },
          oldPassword,
          password
        }
      }
      axios.post("/authManagement/", data,{ headers: {Accept: 'application/json',"Authorization" : `Bearer ${localStorage.getItem('accessToken')}`} })
        .then((response) => {
          resolve(response)
        })
        .catch((error) => { reject(error) })
    })
  },
```

**Comment by claustres** [comment]
Please provide more details about the context and the error, indeed this [test](https://github.com/feathers-plus/feathers-authentication-management/blob/master/test/password-change.test.js#L86) is ok, which seems pretty similar to what you do.

**Comment by farhad-arjmand** [comment]
yes but the response is  ststusCode 400
with message : Expected string value. (authManagement)

**Comment by claustres** [comment]
yes but without context we don't what values/types you provide in email, password, etc.

Provide either a complete example or more information.

**Comment by farhad-arjmand** [comment]
i want to test this article https://hackernoon.com/setting-up-email-verification-in-feathersjs-ce764907e4f2

with axios and HTTP fetch:
```

changePassword({ commit }, {email,oldPassword,password}) {
    return new Promise((resolve, reject) => {
      let data = {
        'action': 'passwordChange',
        'value': {

          'user': {
            email: email
          },
          oldPassword,
          password
        }
      }
      axios.post("/authManagement/", data,{ headers: {Accept: 'application/json',"Authorization" : `Bearer ${localStorage.getItem('accessToken')}`} })
        .then((response) => {
          resolve(response)
        })
        .catch((error) => { reject(error) })
    })
  },
```

and resopnse this message: statusCode: 400

`Expected string value. (authManagement)`

**Comment by cantoute** [comment]
I've got many other issues with trying to implement authentification management with current feathersjs (ts)

I appreciate the effort of those who already done a lot, but without proper usable exemple it results in a lot of waisted time/frustration.

I'm willing to help put a a proper usable exemple.

It's really frustrating working with tools of that level and to be there having to do black magics and re-invent the weal when coming to do something as exotic as users change password process !

feathersjs is close to 50k downloads a week and user change/forgot password is in black magic?
Perhaps we could be not so selfish and share our efforts to put a a working exemple?

As I'm no black magic expert, I can help but will need some guidance.

Anyone who got this working with feathers in typescript would be willing to help me put a working exemple?

**Comment by claustres** [comment]
@cantoute I don't know if your difficulties are related to TS or simply the module usage. As far as I can see there are already some articles detailing how to use it like [1](https://blog.feathersjs.com/how-to-setup-email-verification-in-feathersjs-72ce9882e744#.4ebe36eqp), [2](https://blog.feathersjs.com/how-to-setup-email-verification-in-feathersjs-2-client-side-6082ce0da55e) or [3](https://hackernoon.com/setting-up-email-verification-in-feathersjs-ce764907e4f2) in addition with the [docs](https://github.com/feathers-plus/feathers-authentication-management/blob/master/docs.md).

Sometimes part of these materials can be outdated depending on the Featers version but the principles still remains and it seems to me that the API has not changed much so that it can be easily adapted. As a consequence I can't really approve "user change/forgot password is in black magic". Moreover this is Open Source software, you can open the box and look at what is inside, eg password change operation is a [couple of lines of code](https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/password-change.js#L15), I see no black magic here. If errors are raised you can simply put some breakpoint in the relevant operation and identify where it comes from so that you can correct your code or open issue with relevant information to help you.

This module is a community supported module not part of the FeathersJS core so you can help providing an up-to-date example if you think we need it. IMHO what is missing is probably a global chart explaining how the different operations relate to each others.

**Comment by cantoute** [comment]
Hi @claustres 

Thanks for your message.
I'm hitting many many issues.
One was about typescript, the feathers-authentication-management-ts helped.
Next thing is that all bits of exemple are mostly outdated... and only comes in bits.
I'm sorry, but this https://hackernoon.com/setting-up-email-verification-in-feathersjs-ce764907e4f2 is not of much help.  I would actually call it a waist of time!!

There isn't a usable functional exemple... that seams so unbelievable at this level.
Someone did share an implementation, and I want to thank @meditatingdragon for sharing his code.
follow up https://github.com/MohammedFaragallah/feathers-authentication-management-ts/issues/4

> This module is a community supported module not part of the FeathersJS core so you can help providing an up-to-date example if you think we need it. IMHO what is missing is probably a global chart explaining how the different operations relate to each others.

Been working on it... But still a long way to go https://github.com/cantoute/feathers-authentication-management-ts-example
Does it seem logic that as a first time setting this up I have to do a 'How To' ?

I'm not pointing out those who have yet done a lot for this framework.  I'm pointing out that it can't be that I'm the first one hitting this issue.  I'm sure many have implemented all this in their apps... Are they keeping it for them self?
I know we are part of a society of 99.9% selfish bastards that are happy to take all they can from those who give and not give nothing back... but it always heart to face it so 

Second question:
Is it like we are doing computing for computers or for humans ?

Been in IT business for over 20 years.
Frameworks I used had this implemented from scratch and would take no more then a couple hours to get your app to work for humans (yes and humans forget their password or change email)
Now to have spent 2 weeks implementing lost password for an app that took 5 days to build drives me totally crazy.

**Comment by claustres** [comment]
I am not familiar with TS but it seems to me this module has a pretty simple interface, a single service with a couple of operations as detailed [here](https://github.com/feathers-plus/feathers-authentication-management/blob/master/docs.md#using-feathers-method-calls). It should not be a big deal otherwise I will start to believe TS will hardly support large projects ;-)

Authorization management (aka roles) is a really different beast than authentication, it really depends on what is your use case. For instance we propose an approach for role management here https://blog.feathersjs.com/access-control-strategies-with-feathersjs-72452268739d but it might not apply to all use cases.

According to Separation of Concerns (SoC) it would not be great to add some role management in this module, this should be something not intrusive to be flexible enough. IMHO you can easily add role management using eg https://github.com/feathersjs-ecosystem/feathers-permissions or CASL directly.

**Comment by cantoute** [comment]
> I was wondering if it would be worth integrating some basic role management at same time ?
It could be a nice kit for newbees like me :)

Seems I wasn't very clear, here I ment integrating some form of role management in the exemple, not in auth module :)

The idea would be to have an exemple with most of what are very common things for most apps to have (aka: made for human users).
A clean implementation of authManagement + a role management fairly simple yet that covers most common use case.
It's kind of starter kit I would love to find...

**Comment by jurnet** [comment]
Hello, 
I've got the same problem with axios : for example
`    const payload={
        "action": "verifySignupLong",
        "token": "58893d753824437c8b8f3fc9c517df"
    }

    axios.post(API_BASE_URL+'/authManagement', payload)
        .then(function (response) {
            if(response.status === 200 || response.status === 201){
            } else{
                alert.error(`${t('alert.error')}`);
            }
        })
        .catch(function (error) {
            alert.error(`${t('alert.authenticate-false')}`);
        });`

And error in console : 
`className: "bad-request"
code: 400
data: {}
errors: {$className: "badParams"}
$className: "badParams"
message: "Expected string value. (authLocalMgnt)"
name: "BadRequest"`
