### ISSUE TITLE
Example passwordless app using SMS  for login and account creation

### ISSUE THREAD

**Issue by mroushdy** [feathers-plus/feathers-authentication-management#139]
I am building an app that is passwordless. The only method of signing up and login is by entering a phone number and verifying that number with a code. I am pulling my hair trying to figure out how to do it with this app. Can anyone please give guidance on how to implement this?

**Comment by claustres** [comment]
Actually the way you can send a verification code is pretty similar to the way you can send a verification email. You can find some articles like https://blog.feathersjs.com/how-to-setup-email-verification-in-feathersjs-72ce9882e744 about how to implement a custom notifier doing so. 

It should not be too much complex to replace sending an email containing the verification code by sending a SMS with your API or thrid-party service. However in your case you should use the "short" token versions of the service operations instead of the "long" one usually used in emails.

However I am afraid that your use case is not completely covered out-of-the-box because this module relies on the presence of a password with a dedicated reset operation for instance. But I think you should be able to rely on `verifySignupShort` and `resendVerifySignup` to perform it.
