### ISSUE TITLE
send-reset-pwd.js creates wrong tokens

### ISSUE THREAD

**Issue by lapinzon** [feathers-plus/feathers-authentication-management#140]
The reset tokens are generated preconcatening an user id and then hashing it.

**Comment by claustres** [comment]
What do you mean exactly by "wrong" ? Could you provide moire context or a reproducible sample ? The token is generated like this just to be able to retrieve the user directly from the token as far as I understand.

**Comment by paolotozzo** [comment]
Hi,

+1 on the issue. Seems the resetToken field is stored bcrypted, but the email is sent with an url with a hash that is not, therefore making the verifySignupLong action failing

**Comment by claustres** [comment]
Sorry but we need more context about your use case (module version, feathers version, source code sample, etc.) because as far as I know:
* signup verification is a basic feature used by a lot of people so that this bug should prevent it to work and everybody should have noticed it a long time ago
* all tests are currently passing

As far as I understand it is normal that the token sent to the user is not encrypted and the one store in DB is because the bcrypt compare function is used https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/reset-password.js#L55, just like when you compare a plain password and the encrypted one in DB when you log in. So there is probably something specific that make it work the wrong way in your case.

As you might have noticed this module is looking for new maintainers and I'll do my best to answer issues/PRs but I don't know well all the details in the source code so the more details you can provide the best help I can provide.

**Comment by paolotozzo** [comment]
@claustres Sorry, as it seems your answer is related to my comment, which I then deleted (and I shouldn't have). All solved, it was a bug on my code.

**Comment by OnnoGabriel** [comment]
I guess, we can close this. Or @lapinzon provides more information about why this is an issue.

Yes, the password-reset token is a string composed of the user id AND a random byte string of length ``options.longTokenLen`` (see [send-reset-pwd.js](https://github.com/feathers-plus/feathers-authentication-management/blob/da3f72ea03b770a2fa4803d2c1aa13365675a2a5/src/send-reset-pwd.js)). By doing so there is no chance that two reset tokens are the same (which could happen with just random strings, although very unlikely).

@claustres is also right. The password-reset token is stored in hashed form in the database (like the password) and send to the user in clear text form. As it should.

**Comment by claustres** [comment]
@OnnoGabriel We also use this package in our product, if you'd like to help me maintaining it please tell me I will ask @marshallswain if I can be able to add you to the repo.

**Comment by lapinzon** [comment]
Yes, you are right, it was my lack of understanding and confusion with other versions.

Thanks a lot for your time.

**Comment by OnnoGabriel** [comment]
@lapinzon, glad we solved this issue.

@claustres, as I said, I would be happy to help. Not as the only responsible person, but in a team would be fine with me.
