### ISSUE TITLE
If a user has signed up with oAuth, is there an ability to add/change a password?

### ISSUE THREAD

**Issue by jasondonnette** [feathers-plus/feathers-authentication-management#71]
When a user signs up with oAuth (Facebook, Google, etc), is there a way to later add a regular password?

Assume the user forgets that they signed up with oAuth and tries to do a password reset on their e-mail. The password reset works (and a hashed password shows up on the User model), but the user is unable to log in with the password: `401 not-authenticated, Invalid login`

I the user does a password reset (when logged in), it's not allowed. I've tried with both a blank password (`400 bad-request, Expected string value.`), or with one that they set during a password reset (`400 bad-request, Current password is incorrect.`).

### Expected behavior
There should be some API for adding a password to an account that has previously signed up with oAuth. 

### Actual behavior
There appears to be no way to change or add a password if a user signed up with oAuth.

### System configuration
**Module versions**
`"feathers-authentication-management": "^0.7.0",`

**NodeJS version**:
`8.4.0`

**Comment by eddyystop** [comment]
This repo is not designed to be used any other auth strategy, because feathers-authentication never integrated it. However you should be able to modify it to do so, if for no other reason than its code is rather clean.

Please submit a PR if you do so. Thanks.

**Comment by claustres** [comment]
If the password for the user is correctly generated I can't see why it shouldn't work after a reset. I've just checked in my app and after a login through google if I do a password reset I can login with the new password in local mode instead of using Google. I am using v2.x of this module.

By default it is impossible to reset password if email is not verified, maybe this is the error you get ? You can change this behavior using the `skipIsVerifiedCheck` option when initializing the module. Otherwise if you authenticate a user using eg Google you should set it verified because it will not be by default. 

OR maybe you were talking about password change and not reset ? In this case you first need an initial password.

**Comment by eddyystop** [comment]
I think we can close this issue as it does not appear to me there are outstanding issue. If you have any comments or wish to reopen the issue please post to authenticate-local-management.

Full details on the authenticate-local-management rewrite are posted to https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md
